[app]
name = "failures"
base = "cholesky"
failure_rate = 0.8
failure_type = "memory"

[app.config]
matrix_size = 100
block_size = 50

[engine.executor]
name = "parsl-htex"
retries = 3

[engine.executor.htex.exe1]
max_workers = 4
radio_mode = "diaspora"

[engine.executor.htex.exe1.provider]
kind = "SlurmProvider"
init_blocks = 1
max_blocks = 1
min_blocks = 1
nodes_per_block = 1
partition = "rtx2080ti"
qos = "rtx2080ti"
scheduler_options = "#SBATCH --nodelist=gpu025"
walltime = "00:30:00"

[engine.executor.htex.exe1.provider.launcher]
kind = "SrunLauncher"



[engine.executor.htex.exe2]
max_workers = 4
radio_mode = "diaspora"

[engine.executor.htex.exe2.provider]
kind = "SlurmProvider"
init_blocks = 1
max_blocks = 1
min_blocks = 1
nodes_per_block = 1
partition = "titan"
qos = "titan"
scheduler_options = "#SBATCH --nodelist=gpu030"
walltime = "00:30:00"

[engine.executor.htex.exe2.provider.launcher]
kind = "SrunLauncher"



[engine.executor.monitoring]
hub_address = "localhost"
logging_endpoint = 'sqlite:///parsl-runinfo/monitoring.db'
resource_monitoring_interval = 1
hub_port = 55055