[app]
name = "failures"
base = "cholesky"
failure_rate = 0.3
failure_type = "memory"

[app.config]
matrix_size = 100
block_size = 50

[engine.executor]
name = "parsl-htex"
retries = 3

[engine.executor.htex.exe1]
label = "exe1"
max_workers = 40
radio_mode = "filesystem"

[engine.executor.htex.exe1.provider]
kind = "LSFProvider"
queue = "large"
scheduler_options = ""
walltime = "00:20:00"
bsub_redirection = 1
init_blocks = 1
max_blocks = 1
min_blocks = 1

request_by_nodes = 0
cores_per_block = 640
cores_per_node = 40

[engine.executor.htex.exe1.provider.launcher]
kind = "MpiRunLauncher"
overrides="-ppn 1 -host $(cat $(echo $LSB_DJOB_HOSTFILE) | sort -n | uniq | head -n 2 | paste -d, -s)"


[engine.executor.htex.exe2]
label = "exe2"
max_workers = 40
radio_mode = "filesystem"

[engine.executor.htex.exe2.provider]
kind = "LSFProvider"
queue = "smp"
scheduler_options = ""
walltime = "00:20:00"
bsub_redirection = 1
init_blocks = 1
max_blocks = 1
min_blocks = 1

request_by_nodes = 0
cores_per_block = 40
cores_per_node = 40

[engine.executor.htex.exe2.provider.launcher]
kind = "MpiRunLauncher"
overrides="-ppn 1 -host $(cat $(echo $LSB_DJOB_HOSTFILE) | sort -n | uniq | head -n 2 | paste -d, -s)"


[engine.executor.monitoring]
hub_address = "localhost"
logging_endpoint = 'sqlite:///parsl-runinfo/monitoring.db'
resource_monitoring_interval = 1
hub_port = 55057