[app]
name = "failures"
base = "mapreduce"
failure_rate = 1
failure_type = "import"

[app.config]
data_dir = "/work/cse-zhousc/resilient_compute/resilience_test/taiyi/import/tmp/generated-files"
map_tasks = 3
generate = "True"
generated_files = 10

[engine.executor]
name = "parsl-htex"
retries = 3

[engine.executor.htex.exe1]
label = "exe1"
max_workers = 40
radio_mode = "filesystem"

[engine.executor.htex.exe1.provider]
kind = "LSFProvider"
queue = "large"
scheduler_options = ""
walltime = "00:20:00"
bsub_redirection = 1
init_blocks = 1
max_blocks = 1
min_blocks = 1

request_by_nodes = 0
cores_per_block = 1280
cores_per_node = 40

[engine.executor.htex.exe1.provider.launcher]
kind = "MpiRunLauncher"
overrides="-ppn 1 -host $(cat $(echo $LSB_DJOB_HOSTFILE) | sort -n | uniq | head -n 2 | paste -d, -s)"


[engine.executor.htex.exe2]
label = "exe2"
max_workers = 40
radio_mode = "filesystem"

[engine.executor.htex.exe2.provider]
kind = "LSFProvider"
queue = "short"
scheduler_options = ""
worker_init = 'echo $PATH; export PATH="/work/cse-zhousc/miniconda3/bin:$PATH"; source activate /work/cse-zhousc/miniconda3/envs/taps310;'
walltime = "00:20:00"
bsub_redirection = 1
init_blocks = 1
max_blocks = 1
min_blocks = 1

request_by_nodes = 0
cores_per_block = 40
cores_per_node = 40

[engine.executor.htex.exe2.provider.launcher]
kind = "MpiRunLauncher"
overrides="-ppn 1 -host $(cat $(echo $LSB_DJOB_HOSTFILE) | sort -n | uniq | head -n 2 | paste -d, -s)"


[engine.executor.monitoring]
hub_address = "localhost"
logging_endpoint = 'sqlite:///parsl-runinfo/monitoring.db'
resource_monitoring_interval = 1
hub_port = 55056