[app]
name = "failures"
base = "moldesign"
failure_rate = 0.3
failure_type = "worker-killed"

[app.config]
dataset = '/work/cse-zhousc/resilient_compute/resilience_test/taiyi/debug/data/moldesign/QM9-search.tsv'
initial_count = 4
batch_size = 4
search_count = 16

[engine.executor]
name = "parsl-htex"
retries = 3

[engine.executor.htex]
max_workers = 40
radio_mode = "filesystem"

[engine.executor.htex.provider]
kind = "LSFProvider"
queue = "debug"
scheduler_options = ""
walltime = "00:20:00"
bsub_redirection = 1
init_blocks = 1
max_blocks = 1
min_blocks = 1

worker_init = "export OMP_NUM_THREADS=1; export OPENBLAS_NUM_THREADS=1"
request_by_nodes = 0
cores_per_block = 80
cores_per_node = 40

[engine.executor.htex.provider.launcher]
kind = "MpiRunLauncher"
overrides="-ppn 1 -host $(cat $(echo $LSB_DJOB_HOSTFILE) | sort -n | uniq | head -n 2 | paste -d, -s)"


[engine.executor.monitoring]
hub_address = "localhost"
logging_endpoint = 'sqlite:///parsl-runinfo/monitoring.db'
resource_monitoring_interval = 1
hub_port = 55055