[app]
name = "failures"
base = "cholesky"
failure_rate = 0
failure_type = "worker-killed"

[app.config]
matrix_size = 100
block_size = 50

[engine.executor]
name = "parsl-htex"
retries = 3

[engine.executor.htex.exe1]
max_workers = 4
radio_mode = "filesystem"

[engine.executor.htex.exe1.provider]
kind = "LSFProvider"
init_blocks = 1
max_blocks = 1
min_blocks = 1
nodes_per_block = 1
queue = "debug"
walltime = "00:30:00"



[engine.executor.htex.exe2]
max_workers = 4
radio_mode = "filesystem"

[engine.executor.htex.exe2.provider]
kind = "LSFProvider"
init_blocks = 1
max_blocks = 1
min_blocks = 1
nodes_per_block = 1
queue = "debug"
walltime = "00:30:00"




[engine.executor.monitoring]
hub_address = "localhost"
logging_endpoint = 'sqlite:///parsl-runinfo/monitoring.db'
resource_monitoring_interval = 1
hub_port = 55055